### ISSUE TITLE
Batch processing support for node.js

### ISSUE THREAD

**Issue by dilipkumar2k6** [mscdex/mmmagic#136]
I am using `mmmagic` with my node.js code. Currently my code takes one file buffer content at a time as sample code given below.
```
var Magic = require('mmmagic').Magic;

  var magic = new Magic(),
        buf = new Buffer('import Options\nfrom os import unlink, symlink');
  
  magic.detect(buf, function(err, result) {
      if (err) throw err;
      console.log(result);
  });
```
How can I support batch processing to make it faster? I have requirement to process 1000+ files at a time. Batching will help. I am looking for something as below.
```
var Magic = require('mmmagic').Magic;

  var magic = new Magic(),
     var   buf1 = new Buffer('import Options\nfrom os import unlink, symlink');
    var   buf2 = new Buffer('import Options\nfrom os import unlink, symlink 2');
  magic.detect([buf1, buf2], function(err, results) {
      if (err) throw err;
      console.log(results);
  });
```

**Comment by mscdex** [comment]
Each detection uses a (libuv) thread (because libmagic can do blocking things and the detection itself can take some time) from a thread pool that is shared with the rest of node. There are some possibilities for improving thread reuse and the like, but I have not had time to dive in to find an optimal solution.

**Comment by dilipkumar2k6** [comment]
thank you. For now I will try to use `Promise.all` with `4` promise at a time as my server has `4` core `CPU`.
