### ISSUE TITLE
Add node v4 to travis build

### ISSUE THREAD

**Issue by platy** [mscdex/mmmagic#58]
I'm not sure but maybe there is a build problem for mmmagic on travisci with Node v4.0.0. I notice that your build isn't using it at the moment.

My project is failing on travis when building mmmagic with v4.0.0 but is successful with v0.12. I can also build it at home with v4.0.0 on osx and ubuntu.

Link to the failure -> https://travis-ci.org/platy/spec-verify/jobs/80084896#L462

**Comment by mscdex** [comment]
Your Travis setup is using an [older version of gcc/g++](https://travis-ci.org/platy/spec-verify/jobs/80084896#L17). You need at least g++ 4.8 to build against any io.js version onward (including node v4).

You can ensure g++ 4.8 is used on Travis by adding an appropriate [`addons` section](https://github.com/mscdex/mmmagic/blob/cdcc6bc87aaa66f8103930c8a6ad4e9a7f1e2dc9/.travis.yml#L6-L11) so that g++ 4.8 gets installed and then setting `CXX=g++-4.8` in the environment so that the right version gets used by the build mechanism.

**Comment by mscdex** [comment]
PR inbound: platy/spec-verify#8

**Comment by platy** [comment]
Thanks very much!
