### ISSUE TITLE
TypeError: Magic.setFallback is not a function

### ISSUE THREAD

**Issue by mortzu** [mscdex/mmmagic#64]
When I use our app with mmmagic I get this error: https://sour.is/p/#/HallyZHmQjixCStiHy0FNw!LAdmutlsNqLXU-CJp-PCADNPPsUfvpgIgSogiGEyIy0

**Comment by mscdex** [comment]
Did anything change, such as did you switch to a newer major version of node recently? If so, you may need to rebuild the addon.

**Comment by mortzu** [comment]
I've did without any change

**Comment by mscdex** [comment]
I'm not sure then. If you are able to come up with a way to reproduce the environment so I can test, that would be great. Otherwise I'm not sure what to say since CI is passing on both Linux and OSX, even with node v4.2.

I guess you could also try just reinstalling `mmmagic` and seeing if that helps any.

**Comment by mortzu** [comment]
It was something in my environment. With a clean shell environment it works finde. Sorry for the noise.
