### ISSUE TITLE
 Fails to build on node.js v4 on Travis CI

### ISSUE THREAD

**Issue by iamstarkov** [mscdex/mmmagic#65]
mmmagic [failed to build on Travis CI](https://travis-ci.org/iamstarkov/jsunderhood/builds/87652166#L105)

I’m using [my own fork of node-stream-mmmagic](https://github.com/iamstarkov/jsunderhood/commit/087437f2358d89a0d32ec67bd0f8d565086d3df6) with [latest mmmagic](https://github.com/iamstarkov/node-stream-mmmagic/blob/master/package.json#L30), but it’s still not working. Can you help me?

**Comment by mscdex** [comment]
The compiler is too old. You have to use gcc/g++ 4.8 or newer. You can see how I'm enabling that in this repo's travis config (notable the `addons` part and setting of the `CC` and `CXX` environment variables).

**Comment by iamstarkov** [comment]
should these preparations be done by every mmmagic’s consumer?

**Comment by iamstarkov** [comment]
or is it okay just to add this [addons](https://github.com/mscdex/mmmagic/blob/master/.travis.yml#L6-L11) sections?

**Comment by mscdex** [comment]
No, as that is mostly installing node and `mmmagic`. The gcc/g++ 4.8+ requirement comes from node v4+ and affects all addons.

**Comment by iamstarkov** [comment]
can you add this requirements to the readme?

**Comment by mscdex** [comment]
For testing on Travis, you can copy it if you wish.

For actually *installing* the module by the consumer however, you wouldn't need those particular steps since you would already have node installed and the other command there is the same as `npm install mmmagic`. The gcc/g++ 4.8+ requirement comes from node v4+ and is mentioned in its [readme](https://github.com/nodejs/node/blob/master/README.md).
