### ISSUE TITLE
Accented character in file name?

### ISSUE THREAD

**Issue by bmains911** [mscdex/mmmagic#67]
Is https://github.com/mscdex/mmmagic/blob/master/test/fixtures/t%C3%A9st.txt supposed to have the accented é in its file name?  (Trying to investigate some Jenkins issues with utf8 characters)

Thanks!

**Comment by mscdex** [comment]
Yes, that is intentional and there is a test that uses it. It's to test that files with UTF-8 characters in their filenames are opened/read properly on Windows.

**Comment by dazwin** [comment]
This is causing various problems across different environments/deployments. It seems that this test is based on the filesystems ability to support UTF-8, not mmmagic in isolation - is this really necessary pre-requisite?

**Comment by mscdex** [comment]
> This is causing various problems across different environments/deployments

Can you be more specific?

**Comment by dazwin** [comment]
I've come across this twice now. Most recently with ansible - I'm trying out various fixes per https://github.com/ansible/ansible/issues/11348 as we speak. The other issue may have been Ansible-related as well (but I'll follow up if it was something else).

I understand that all other components, filesystems, OS's etc. _should_ support UTF-8 and do so correctly, but the reality is that they don't and it shouldn't be necessary either (won't there be problems if another system locale is in effect?).

So, I'm just questioning the effectiveness of using a filename containing non-ASCII characters as part of a unit test in general (this package is not meant to test filesystem/OS capabilities), and kindly requesting that it is changed as a practical solution :)

**Comment by dazwin** [comment]
The other time I had this problem was with Atlasssian's Bamboo when it tried to clean up a project directory. I traced this to its use of openjdk-1.7 (still supported as part of Ubuntu 14.04 LTS). Eventually fixed by installing Oracle Java 1.8.

**Comment by mscdex** [comment]
The test exists because Windows users expect to be able to use `mmmagic` with any files Windows supports. libmagic has an issue with opening non-ASCII files on Windows (unsurprising since Windows is not libmagic's main target platform), so `mmmagic` has to workaround that issue by opening the file itself and passing the resulting file descriptor to libmagic. To make sure the workaround works (and continues to work), there needs to be a test. In order to test the workaround you need a file with non-ASCII characters in it.

Besides, any filesystem that doesn't support non-ASCII character encodings isn't worth using anymore.

**Comment by mscdex** [comment]
Closing this unless someone has a (better) solution.
