### ISSUE TITLE
Module version mismatch. Expected 50, got 48

### ISSUE THREAD

**Issue by averissimo** [mscdex/mmmagic#94]
![image](https://cloud.githubusercontent.com/assets/211358/19268801/732b9dca-8fae-11e6-8d27-4c4e23d4e9f2.png)

This error appears in a electron app (YakYak) just by adding `mmm = require('mmmagic')`

I've seen #66 #18 and #17 but still cannot solve this problem :\

I'm using node v6.7.0 and npm 3.10.8, which are the latest version as I'm writing this.

I've tried using node v4 and same error happens.

I've done `npm rebuild` and clearing cache, but problem still persists

Any tips?

**Comment by mscdex** [comment]
The issue here is that `mmmagic` was built using regular node-gyp (which compiles for plain node), but the addon was loaded inside electron, which has its own, separate build tools with its own addon ABI versioning (50 in this case).

I'm not familiar with building node addons for electron, but a quick google search turns up [this electron wiki entry](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md#the-easy-way).

**Comment by averissimo** [comment]
thanks you for the reply. I was way of on my search terms :)
